distributable:
  url: https://hackage.haskell.org/packages/archive/cabal-install/{{ version.raw }}/cabal-install-{{ version.raw }}.tar.gz
  strip-components: 1

versions:
  github: haskell/cabal/releases
  strip: /^[Cc]abal /

dependencies:
  haskell.org: 9
  gnu.org/gmp: 6
  zlib.net: 1

provides:
  - bin/cabal

build:
  dependencies:
    haskell.org: '*'
    curl.se: '*'
    linux/aarch64:
      github.com/numactl/numactl: ^2 # downloaded cabal needs this
    tukaani.org/xz: 5
    linux:
      gnu.org/gcc: '*' # haskell should be using llvm, but it still needs libc++
      gnu.org/binutils: '*' # haskell should be using llvm, but it still wants ld.gold
  script:
    - run: |
        if test ! -e .bootstrap/cabal; then
          if test ! -e .bootstrap; then
            mkdir .bootstrap
          fi
          curl -L "${BOOTSTRAP}" | tar Jxf - -C .bootstrap
        fi

    ## This seems dirty, but building is an internal-only gig atm.
    # Likely fix is to use CABAL_DIR in build scripts
    - run: |
        if test -e ~/.cabal/bin; then
          rm -r ~/.cabal/bin
        fi

    # this is not an acceptable solution, do you know a better one? pls PR ðŸ™
    #FIXME also this sed line sucks but I got bored trying to make it work
    - |
      sed -i \
        -e 's/build-depends: base.*/build-depends: base >=4.10 \&\& <5/' \
        -e 's/text.*>=.*/text       >= 1.2.3    \&\& < 3,/' \
        cabal-install.cabal
    # ^^ SEE https://github.com/haskell/cabal/issues/8118
    - mkdir -p "{{prefix}}/bin"
    - ./.bootstrap/cabal v2-update
    - ./.bootstrap/cabal v2-install
      --install-method=copy
      --installdir={{prefix}}/bin
      $ADDITIONAL_CABAL_FLAGS
  env:
    darwin/aarch64:
      BOOTSTRAP: https://downloads.haskell.org/~ghcup/unofficial-bindists/cabal/3.6.0.0/cabal-install-3.6.0.0-aarch64-darwin-big-sur.tar.xz
    darwin/x86-64:
      BOOTSTRAP: https://downloads.haskell.org/~cabal/cabal-install-3.2.0.0/cabal-install-3.2.0.0-x86_64-apple-darwin17.7.0.tar.xz
    linux/x86-64:
      BOOTSTRAP: https://downloads.haskell.org/~cabal/cabal-install-3.2.0.0/cabal-install-3.2.0.0-x86_64-unknown-linux.tar.xz
    linux/aarch64:
      BOOTSTRAP: https://downloads.haskell.org/ghcup/unofficial-bindists/cabal/3.7.0.0-pre20220407/cabal-install-3.7-aarch64-linux-deb10.tar.xz
    linux:
      ADDITIONAL_CABAL_FLAGS:
        - -v3
        # else segfaults
        - --enable-relocatable
        - --ghc-option=-fPIC
        - --ghc-option=-optl=-pie
      AR: ${{deps.llvm.org.prefix}}/bin/llvm-ar

test:
  - cabal --config-file=./config user-config init
  - cabal --config-file=./config info Cabal
